remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
layout: minimal
title: Marine Invertebrate Microbiome Project
nav_order: 4
has_children: true
